{% set version = "0.16.0" %}
{% set filename = "apache-arrow-" + version + ".tar.gz" %}
{% set checksum = "261992de4029a1593195ff4000501503bd403146471b3168bd2cc414ad0fb7f5" %}
{% set number = "3" %}
{% set cuda_enabled = cuda_compiler_version is not undefined and cuda_compiler_version == '9.2' %}
{% set build_ext = "cuda" if cuda_enabled else "cpu" %}

package:
  name: pyarrow-ext
  version: {{ version }}

source:
  fn: {{ filename }}
  url: https://dist.apache.org/repos/dist/release/arrow/arrow-{{ version }}/{{ filename }}
  sha256: {{ checksum }}

build:
  skip: true            # [win32]
  skip: true            # [win and py<35]
  skip: true            # [linux and cuda_compiler_version is not undefined and cuda_compiler_version != '9.2' and cuda_compiler_version != 'None']
  number: {{ number }}

outputs:
  - name: pyarrow
    script: build-pyarrow.sh  # [not win]
    script: bld.bat           # [win]
    version: {{ version }}
    build:
      number: {{ number }}
      string: "py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ number }}_{{ build_ext }}"
      skip: true              # [win32]
      skip: true              # [win and py<35]
      skip: true              # [linux and cuda_compiler_version is not undefined and cuda_compiler_version != '9.2' and cuda_compiler_version != 'None']
      track_features:
        - arrow-cuda          # [linux and cuda_compiler_version is not undefined and cuda_compiler_version == '9.2']

    requirements:
      build:
        - cmake
        - ninja
        - make                # [unix]
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        # pyarrow does not require nvcc but it needs to link against libraries in arrow-cpp=*=*cuda
        - {{ compiler("cuda") }}  # [linux and cuda_compiler_version is not undefined and cuda_compiler_version == '9.2']
      host:
        # directly pin boost-cpp as we also seem to directly include boost symbols
        # in the Python modules.
        - arrow-cpp {{ version }}
        - boost-cpp
        - cython
        - numpy 1.16.*
        - python
        - setuptools
        - setuptools_scm
        - six
      run:
        - {{ pin_compatible('numpy', lower_bound='1.16') }}
        - boost-cpp
        - futures  # [py==27]
        - glog
        - pandas
        # empty parquet-cpp metapackage, force old versions to be uninstalled
        - parquet-cpp 1.5.1.*
        - python
        - six
        - snappy
      run_constrained:
        - arrow-cpp-proc * {{ build_ext }}

    test:
      imports:
        - pyarrow
        - pyarrow.dataset  # [not py==27]
        - pyarrow.flight   # [not py==27]
        - pyarrow.gandiva  # [(not py==27) and (not (aarch64 or ppc64le))]
        - pyarrow.orc      # [unix]
        - pyarrow.parquet
        - pyarrow.plasma   # [unix]
        - pyarrow.fs
        - pyarrow._s3fs
        - pyarrow._hdfs
        - pyarrow.cuda     # [linux and cuda_compiler_version is not undefined and cuda_compiler_version == '9.2']

    about:
      home: http://github.com/apache/arrow
      license: Apache-2.0
      license_file: LICENSE.txt
      summary: 'Python libraries for Apache Arrow'

about:
  home: http://github.com/apache/arrow
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: 'Python libraries for Apache Arrow'

extra:
  recipe-maintainers:
    - wesm
    - xhochy
    - jreback
    - cpcloud
    - pcmoritz
    - robertnishihara
    - siddharthteotia
    - kou
    - kszucs
    - pitrou
    - pearu
